POST http://localhost:3002/register
Content-Type: application/json

{
  "username": "adadmmm_richard",
  "name": "Adam Richard",
  "password": "123456",
  "gender": "male",
  "location": "Detroit"
}
###
//API 2
POST http://localhost:3002/login
Content-Type: application/json

{
  "username": "adadmmm_richard",
  "password": "1234356"
}
###
PUT http://localhost:3002/change-password
Content-Type: application/json

{
  "username": "adam_richard",
  "oldPassword": "richard_567",
  "newPassword": "richard@123"
}
